### ISSUE TITLE
[Oppia Web] Unable to Access Math Classroom - 404 Error on http://localhost:8181/learn/math"

### ISSUE THREAD

**Issue by hrshkshri** [oppia/oppia-web-developer-docs#218] opened 2023-12-28 05:07 UTC
New contributors setting up Oppia are experiencing difficulties accessing the Math Classroom at http://localhost:8181/learn/math. There is currently no guidance provided in the Wiki [How to access Oppia webpages](https://github.com/oppia/oppia/wiki/How-to-access-Oppia-webpages) on how to address this issue.
![Screenshot 2023-12-28 at 10 47 51 AM](https://github.com/oppia/oppia-web-developer-docs/assets/108923011/b88882a1-5bc0-417a-903f-8657ecd39249)

**Comment by gp201** [comment] 2024-01-08 05:08
Note: There is currently one method outlining how to do it. https://github.com/oppia/oppia/wiki/How-to-access-Oppia-webpages#topic-editor-including-preview-tab
However, I assume the solution you're looking for is https://github.com/oppia/oppia-web-developer-docs/issues/232, which is not in the wiki.

Please let me know if this is correct @hrshkshri

**Comment by gp201** [comment] 2024-01-08 05:14
Duplicate of https://github.com/oppia/oppia-web-developer-docs/issues/232

**Closed as not planned by gp201** 2024-01-08 05:14 UTC
Labels: Impact: High, Work: Low
