### ISSUE TITLE
Fold "Formatters" and "Bytes and string handling in Python 3" pages into "Coding style guide"

### ISSUE THREAD

**Issue by U8NWXD** [oppia/oppia-web-developer-docs#337] opened 2024-06-23 13:42 UTC
The following pages should be folded into https://github.com/oppia/oppia/wiki/Coding-style-guide:
* https://github.com/oppia/oppia/wiki/Formatters
* https://github.com/oppia/oppia/wiki/Bytes-and-string-handling-in-Python-3

**Comment by gutoslv** [comment] 2024-11-16 13:09
Hey, I'm working on it on the PR [408](https://github.com/oppia/oppia-web-developer-docs/pull/408#pullrequestreview-2440310218), could you please assign this issue to me?

**Comment by augusto-silva-deel** [comment] 2024-11-18 11:48
hey @U8NWXD the PR is now closed, I believe we can close this issue.

**Comment by gutoslv** [comment] 2024-11-18 11:51
hey @U8NWXD the PR is now closed, may you check if the issue is fixed and close the issue if so?

I'm available to fix any remaining issue in order to close this issue.

**Comment by seanlip** [comment] 2024-11-18 12:12
It looks good @gutoslv -- I think, in general, you just need to make sure the issue is linked in the "Development" section of the right sidebar if you want to ensure it gets closed. Thanks for checking on this!

**Closed as completed by seanlip** 2024-11-18 12:12 UTC
Labels: enhancement, good first issue, Impact: Medium, Work: Low
