### ISSUE TITLE
Fold "Glossary of Terms" and "User Documentation" into "How to Access Oppia Webpages"

### ISSUE THREAD

**Issue by U8NWXD** [oppia/oppia-web-developer-docs#335] opened 2024-06-23 13:37 UTC
Fold https://github.com/oppia/oppia/wiki/Glossary-of-terms into https://github.com/oppia/oppia/wiki/How-to-access-Oppia-webpages. Remove https://oppia.github.io from the sidebar and instead link to it from the "How to access Oppia webpages" page

**Comment by U8NWXD** [comment] 2024-06-23 13:37
@seanlip should we keep https://oppia.github.io/ as a separate site at all? I like the idea of having user documentation separate from our more technical wiki, but we haven't done a good job of keeping https://oppia.github.io/ up to date

**Comment by seanlip** [comment] 2024-06-23 13:40
I think it's better to keep it as a separate site and use it for user-facing documentation; keeping it up-to-date would be a separate project. (I don't think we want end users to have to read a github wiki)

**Comment by micga818** [comment] 2024-09-18 07:10
I would like to work on this issue but I don't fully understand what the issue is exactly. Just to clarify, should the "Glossary of Terms" page be added as part/ subheading of the "How to Access Oppia Webpages" page?
(So it would be visible under the table of contents of the "How to Access Oppia Webpages" page)
From your discussion it sounds like the "User Documentation" page should be kept as it is.
@seanlip @U8NWXD

**Comment by seanlip** [comment] 2024-09-26 19:30
Hi @micga818, sorry for the late reply. Yes, the "User Documentation" page should be kept as it is. 

The aim of this issue is to combine the glossary and "how to access" pages, but not just by adding a new subheading. If you look at the latter page, you'll see that there is a section near the top called "Overview of entities". It would be helpful to merge any useful info from the "Glossary" page into that, so that we can remove the Glossary page completely.

Also, if you'd like to work on this issue, then per the guidance at https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue, please provide an explanation of what your PR will do (with names of files you're changing, what you plan to change in each file, etc.). If it looks good, we can assign you to this issue. Please also follow the other instructions on that wiki page if you have not yet done so. Thanks!

**Comment by gutoslv** [comment] 2024-11-16 15:50
I'm working on these changes via the PR #415, may you assign it to me?

Thanks in advance.

**Comment by gutoslv** [comment] 2024-11-18 11:50
hey @U8NWXD the PR is now closed, may you check if the issue is fixed and close the issue if so?

I'm available to fix any remaining issue in order to close this issue.

**Comment by seanlip** [comment] 2024-11-18 12:12
This looks good, closing. Thanks!

**Closed as completed by seanlip** 2024-11-18 12:12 UTC
Labels: enhancement, good first issue, Impact: Medium, Work: Low
