### ISSUE TITLE
Link to Example Code for CSS is Broken

### ISSUE THREAD

**Issue by seoeunHong** [oppia/oppia-web-developer-docs#157] opened 2023-04-13 14:06 UTC
Hello,

When I tried to contribute to this project, I was asked to convert CSS to a component. Since I wasn't sure how to do it, I looked up the code style guide document. There was [guideline](https://github.com/oppia/oppia/wiki/Coding-style-guide#css) for this and had link to example code, but the link provided in the document is broken, so I wasn't able to modify my code as per the maintainer's request.

Could you please update the link to a working document? Thank you.

**Comment by nicoleSosa** [comment] 2023-04-15 23:54
@seanlip I was able to get the same error and the error mentioned that the 'oppia/oppia' repository doesn't contain the 'core/templates/components/summary_tile/exploration_summary_tile_directive.html' path in '37a43ca249ffd2b60bf98f791995048ce0ec5269' as shown in screenshot below. 

<img width="1392" alt="Screen Shot 2023-04-15 at 7 49 28 PM" src="https://user-images.githubusercontent.com/83420994/232258783-a725f279-52b3-4984-a436-7838c10f45c3.png">

Then I looked through the codebase and I think I found a file with a similar name that could be the file 'exploration-summary-tile.component.html' at this path 'Oppia/core/templates/components/summary-tile/exploration-summary-tile.components.html.'

<img width="1363" alt="Screen Shot 2023-04-15 at 7 52 49 PM" src="https://user-images.githubusercontent.com/83420994/232258873-647acfba-b08b-4181-bd2f-db4c7586893c.png">


Is this the correct file and if it is, can I be assigned the issue to fix the link? 

Thank you!

**Comment by gp201** [comment] 2023-04-16 19:00
@seoeunHong @nicoleSosa Nice catch! It looks like we will have to update the Coding style wiki page. Thanks for bringing this up!

**Comment by U8NWXD** [comment] 2023-04-25 12:47
> Is this the correct file and if it is, can I be assigned the issue to fix the link?

@nicoleSosa yes that's the correct file. I've assigned you! When do you expect to fix this issue?

**Comment by nicoleSosa** [comment] 2023-04-25 22:59
@U8NWXD Thank you for assigning me the issue. I expect to fix this issue by tomorrow.

**Comment by U8NWXD** [comment] 2023-04-26 16:46
Thanks! I set an expected completion date of Apr 29 to allow for time to get the PR merged

**Comment by nicoleSosa** [comment] 2023-04-26 18:50
@U8NWXD I think the issue is already fixed because when I try reproducing the issue and went to this [guideline page](https://github.com/oppia/oppia/wiki/Coding-style-guide#css). I noticed that the link for example code is fixed with this [link](https://google.github.io/styleguide/htmlcssguide.html#Hexadecimal_Notation).

**Comment by U8NWXD** [comment] 2023-04-26 18:53
I think the broken link is in the last bullet point:

> * For directives, include the CSS in the directive template file, similar to what we do in [this file](https://github.com/oppia/oppia/blob/37a43ca249ffd2b60bf98f791995048ce0ec5269/core/templates/components/summary_tile/exploration_summary_tile_directive.html). (Note that, in this case, all CSS rules should start with the top-level CSS class of the directive, so that they don't affect other elements outside it.) All other CSS should go in core/templates/css/oppia.css.

The "this file" link is broken

**Comment by gp201** [comment] 2023-04-26 19:13
@U8NWXD Do we still use directives, and under what conditions do we expect developers to include the CSS within the file? Since we are now creating separate `.css` files

**Comment by nicoleSosa** [comment] 2023-04-26 19:25
@U8NWXD I understand now. I will fix it right now. Thank you.

**Comment by nicoleSosa** [comment] 2023-04-26 19:53
@U8NWXD I submitted a pull request for this issue . Thank you for your help.

**Closed as completed** 2023-04-27 15:24 UTC
Labels: bug, Impact: Low, Work: Low
